### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'warn'

### ISSUE THREAD

**Issue by saraedum** [conda-forge/pytest-benchmark-feedstock#6]
The pin for pytest might be incorrect.
```
`AttributeError: 'Config' object has no attribute 'warn'`, as reported at https://github.com/ionelmc/pytest-benchmark/issues/147.
```

To reproduce:
```
$ conda create -n pytest pytest-benchmark
[...]
  atomicwrites       conda-forge/noarch::atomicwrites-1.3.0-py_0
  attrs              conda-forge/noarch::attrs-18.2.0-py_0
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2018.11.29-ha4d7672_0
  certifi            conda-forge/linux-64::certifi-2018.11.29-py37_1000
  libffi             conda-forge/linux-64::libffi-3.2.1-hf484d3e_1005
  libgcc-ng          conda-forge/linux-64::libgcc-ng-7.3.0-hdf63c60_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-7.3.0-hdf63c60_0
  more-itertools     conda-forge/linux-64::more-itertools-4.3.0-py37_1000
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1b-h14c3975_0
  pluggy             conda-forge/noarch::pluggy-0.9.0-py_0
  py                 conda-forge/noarch::py-1.8.0-py_0
  pytest             conda-forge/linux-64::pytest-4.3.0-py37_0
  pytest-benchmark   conda-forge/linux-64::pytest-benchmark-3.0.0-py37_1001
  python             conda-forge/linux-64::python-3.7.1-h381d211_1002
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  setuptools         conda-forge/linux-64::setuptools-40.8.0-py37_0
  six                conda-forge/linux-64::six-1.12.0-py37_1000
  sqlite             conda-forge/linux-64::sqlite-3.26.0-h67949de_1000
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1000
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004
[...]
$ conda activate pytest
$ touch test.py
$ pytest test.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/_pytest/config/__init__.py", line 639, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pytest_benchmark/plugin.py", line 1092, in pytest_configure
INTERNALERROR>     config._benchmarksession = BenchmarkSession(config)
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pytest_benchmark/plugin.py", line 568, in __init__
INTERNALERROR>     self.logger = Logger(self.verbose, config)
INTERNALERROR>   File "/home/jule/proj/conda/miniconda3/envs/pytest/lib/python3.7/site-packages/pytest_benchmark/plugin.py", line 519, in __init__
INTERNALERROR>     self.pytest_warn = config.warn
INTERNALERROR> AttributeError: 'Config' object has no attribute 'warn'
```

If it matters, `conda info` produces
```
     active environment : pytest
    active env location : /home/jule/proj/conda/miniconda3/envs/pytest
            shell level : 2
       user config file : /home/jule/.condarc
 populated config files : /home/jule/.condarc
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/jule/proj/conda/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jule/proj/conda/miniconda3/pkgs
                          /home/jule/.conda/pkgs
       envs directories : /home/jule/proj/conda/miniconda3/envs
                          /home/jule/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/3.7.1 Linux/4.20.10-arch1-1-ARCH arch/rolling glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by esloch** [comment]
Fix to in PR #7.
